### ISSUE TITLE
BBCode AST

### ISSUE THREAD

**Issue by TheoryOfNekomata** [syntax-tree/ideas#10]
Considering there is already **hast** for HTML, I think an HTML-derived language like BBCode could also be implemented with some of the tweaks from generating HTML syntax trees.

The differences between BBCode and HTML is that the former:
* Can have custom tags
* Has a different implementation of certain tags, such as `url` (`[url]https://example.com[/url]` and `[url=https://example.com]Foobar[/url]`) `img` (`[img]https://example.com/image.jpg[/img]`)
Relevant links:
* https://www.phpbb.com/community/help/bbcode

**Comment by wooorm** [comment]
Interesting.

What kind of tools do you expect to work on a bbcode AST?

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @TheoryOfNekomata!
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/syntax-tree/unist/discussions/categories/ideas will be the home for ideas going forward.
