### ISSUE TITLE
ast utility function to create selector from passing a root and a leaf node.

### ISSUE THREAD

**Issue by lifeiscontent** [syntax-tree/ideas#2]
it would be nice to have a utility to create a selector from a root.

E.g. `selectorFromTree(root, node); // returns html > body > div:nth-child(1) > h1`

which in turn you could then use something like https://github.com/syntax-tree/hast-util-select

later to find that same node.

the use case I'm using this for is dragging and dropping AST Nodes in a tree and looking them up by paths for mutation of the AST.

CC: @wooorm 

I would personally work on this, but I don't think I know enough about AST manipulation to write a helper like this efficiently.

**Comment by wooorm** [comment]
Sorry I never responded (other than an emoji), but I think this is cool! Still up for building it, or anyone else?

How can I help?

**Comment by lifeiscontent** [comment]
@wooorm if you can either teach me how to write a function that traverses the AST, or maybe we could pair and I could setup the expectations for the function?

**Comment by ChristianMurphy** [comment]
@lifeiscontent you could use https://unifiedjs.com/explore/package/unist-util-visit-parents as a building block or as a template for walking the tree.

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @lifeiscontent!
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/syntax-tree/unist/discussions/categories/ideas will be the home for ideas going forward.
