### ISSUE TITLE
XML AST

### ISSUE THREAD

**Issue by revolunet** [syntax-tree/ideas#4]
see https://github.com/unifiedjs/ideas/issues/2

**Comment by wooorm** [comment]
If someone is interested in doing this, I can help out / mentor!

**Comment by ChristianMurphy** [comment]
https://github.com/syntax-tree/xast

**Comment by revolunet** [comment]
Thanks !!

**Comment by wooorm** [comment]
Currently not focussed on creating a parser, so there is no rexml yet, but I did the `xast-util-to-xml` part!
