### ISSUE TITLE
LaTeX AST

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/ideas#6]
LaTeX is a typesetting language focusing on scientific and technical documents.
https://www.latex-project.org

These could be good starting points for parsing
https://github.com/artcompiler/L15
https://github.com/siefkenj/latex-parser

**Comment by wooorm** [comment]
Awesome! 👍

**Comment by michael-brade** [comment]
Wow, this is great. I will eventually implement an AST for [LaTeX.js](https://github.com/michael-brade/LaTeX.js) as well. Maybe we can share some of the results.

**Comment by Ir1d** [comment]
@michael-brade Looking forward to this :+1:

**Comment by wooorm** [comment]
I don’t think anyone is currently working on this, other than you! I’d love to see this happen!

**Comment by michael-brade** [comment]
well, apparently someone already did start working on this, I just found it: https://github.com/tamuratak/latex-utensils

Looks great :grin:

**Comment by Ir1d** [comment]
This is brilliant. In the `Used` section of Github I noticed that this is used in the [famous plugin for writing latex in vscode](https://github.com/James-Yu/LaTeX-Workshop). I've been using this plugin for several years and I have to say that it works perfectly.

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @ChristianMurphy!
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/syntax-tree/unist/discussions/categories/ideas will be the home for ideas going forward.
