### ISSUE TITLE
Semantic version control

### ISSUE THREAD

**Issue by kskyten** [syntax-tree/ideas#8]
[SemanticMerge](http://www.semanticmerge.com/) is a version control tool based on syntax trees. I haven't tried it personally, but it seems really nice. Unlike git, for example, the diffing algorithm is able to consider the structure of the language to make smarter merges. It supports adding [external parsers](https://users.semanticmerge.com/documentation/external-parsers/external-parsers-guide.shtml#Externalparsers). It would be awesome to be able to convert unist syntax trees to SemanticMerge format.

**Comment by wooorm** [comment]
Interesting!

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @kskyten !
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/syntax-tree/unist/discussions/categories/ideas will be the home for ideas going forward.
