### ISSUE TITLE
C Language AST

### ISSUE THREAD

**Issue by wnayes** [syntax-tree/ideas#9]
I'm interested in doing some C Language parsing / transformations / compilation within a browser environment. I was curious if the unified js ecosystem would be a good fit, to tie into something standardized instead of doing ad hoc development.

If I'm understanding the current ecosystem, C might fit in as:

- `cast`: Specification for a C AST in `unist` format.
- `rec`: C processor
    - `rec-parse`: Parse C files into syntax trees
- `cast-to-x86`: A utility to compile a C AST into an assembly language. (Example of something related to compilation. Maybe it would be more flexible to have another AST for x86 in this example, instead of directly going from C AST to assembly instructions?)

**Comment by wooorm** [comment]
- You may be interested in https://github.com/shawnbot/unist-sitter
- We don‘t have “programming” language parsers yet, we mostly focus on markup languages
- But I think it’s doable!

**Comment by ChristianMurphy** [comment]
Thanks for starting the discussion @wnayes!
We're in the process unifying ideas in with discussions unifiedjs/collective#44
If you'd like to continue this thread, or start a new one https://github.com/syntax-tree/unist/discussions/categories/ideas will be the home for ideas going forward.
